### ISSUE TITLE
Menü elem nem mindenhol megy

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#13]
Balos menünél a menüelemre kattintáskor nem csak a grid nézet lehet. A szükséges nézet neve a content_template elemben van a válasz json-ban. Pl programbeállítások/fordítások, statisztikák alatt minden a stat sablont kéri

Jelenleg a sablon 3 féle lehet:
grid
form_layout
stat

**Comment by ymycorp** [comment]
Statisztikák/ alap statisztikák nem megy, mert kell a stat nevű sablon.
A sablon jelenlegi forrása ez:


{include once file='form_element.tpl'}
{$date_fields = array('datepickerFrom','datepickerTo')} 
{include file='datetime_picker.tpl'} 
<div class="box box-default">
    <div class="box-body">
        <div class="col-md-12">
            <div id="calendar" class="panel">
                <form id="calendar_form" class="form-inline" action="{$self_url}" method="post" id="calendar_form">
                    <div class="row">
                        <div class="col-lg-5">
                            <div class="btn-group">
                                <button class="btn btn-default btn-sm" type="submit" name="submitDateDay">{$predefined_periods.day}</button>
                                <button class="btn btn-default btn-sm" type="submit" name="submitDateMonth">{$predefined_periods.month}</button>
                                <button class="btn btn-default btn-sm" type="submit" name="submitDateYear">{$predefined_periods.year}</button>
                                <button class="btn btn-default btn-sm" type="submit" name="submitDateDayPrev">{$predefined_periods.day_1}</button>
                                <button class="btn btn-default btn-sm" type="submit" name="submitDateMonthPrev">{$predefined_periods.month_1}</button>
                                <button class="btn btn-default btn-sm" type="submit" name="submitDateYearPrev">{$predefined_periods.year_1}</button>
                            </div>
                            {if isset($XLSExport)}
                                <a class="noajax" href="{$xls_link}" >
                                    <span class="btn btn-default"><i class="fa fa-file-excel-o"></i> {$export_list}</span> 
                                </a>
                            {/if} 
                        </div>
                        <div class="col-lg-7">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <div class="input-group">
                                                <label class="input-group-addon">{$from}:</label>
                                                <input id="datepickerFrom" class="datepicker form-control hasDatepicker" name="datepickerFrom" value="{$stats_date_from}" type="text">
                                            </div>
                                        </div>
                                        <div class="col-xs-6">
                                            <div class="input-group">
                                                <label class="input-group-addon">{$to}:</label>
                                                <input id="datepickerTo" class="datepicker form-control hasDatepicker" name="datepickerTo" value="{$stats_date_to}" type="text">
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="row">
                                        <button id="submitDatePicker" class="btn btn-default" type="submit" name="submitDatePicker">
                                            <i class="fa fa-floppy-o"></i>
                                            {$save}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>             
            </div>   
        </div>
        {if  !empty($navigation_list)}
            <div class="col-md-2">
                <fieldset>
                    <legend><i class="fa fa-bar-chart"></i>
                        {$navigation}
                    </legend>

                    {foreach $navigation_list AS $request}
                        <p>- <a href="{$request.url}">{$request.name}</a></p>
                        {/foreach}

                </fieldset>
            </div>
        {/if}
        <div id="stat-content" class="col-md-{if !empty($navigation_fields) || !empty($navigation_list)}10{else}12{/if}">
            {include once file='form_layout.tpl' fields=$fields}
        </div>
    </div>
</div>

**Comment by kailniris** [comment]
Szükségem lenne itt pár módosításra @ymycorp :

- predefined_periods legyen tömb és az elemek objektumok legyenek label és value tulajdonsággal.
-  submitDateDayPrev submitDateYearPrev stb elküldendő kulcs helyett submitDatePrev kulcsot keljen elküldeni értékként pedig a predefined_periods értékét.

**Comment by ymycorp** [comment]
Elvileg kész van. Ki kéne próbálni.
