### ISSUE TITLE
Melléklet elemnél az üzenetek nem jók

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#21]
A melléklet elemnél az üzeneteknek a attachment_texts ből kell jönni ami az első betöltésnél jön le(get_content : 1)
E helyett a statikus elem helyett:
title: 'Melléklet törlése',
            message: 'Biztosan törölni akarja a mellékletet?',
            ok: 'Törlés',
            cancel: 'Mégse',

ha kellenek valahová majd még ilyen szövegek, akkor jelezd és beteszem őket ebbe a json-ba.

**Comment by kailniris** [comment]
Ezeket a szövegeket lehetne tárolni a form adott elemének adatai között?

**Comment by ymycorp** [comment]
Jelenlegi architektúra csak ezt a megoldást támogatja. Nem tudom máshogy
megoldani.

Üdvözlettel: / Best regards, / Cordialement, / Mit freundlichen Grüssen:
 Ádám Imre
