### ISSUE TITLE
A table elemnél nem mindig legyen datatable

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#28]
A table elemnél nem mindig legyen datatable, csak akkor ha van egy datatable:1 elem.
Sok helyen nem lesz megfelelő a datatable, egy sima táblázat jobb.

**Comment by kailniris** [comment]
@ymycorp Hogy működik itt a megkülönböztetés? Hol keressem a datatable:1 elemet?

**Comment by ymycorp** [comment]
Vegyük külön legyen a table, és a datatable elem külön.
