### ISSUE TITLE
Nyelv választós inputok textLang és textareaLang

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#29]
A paraméter beállítások/partner kategóriák alatt van ilyen elem.
A value ilyenkor egy tömb, ahol a tömb elemek az adott nyelvi jelentések, a kulcs pedig a nyelv azonosító.
A nyelvek neve és azonosítója az első bejelentkezés utáni json-ból jönnek (languages elem). Jelenleg úgy van, hogy kitesz annyi mezőt ahány nyelv van de csak a lang_default elem által jelzett látszik alapból, a többi rejtett, míg ki nem választjuk. Ha egy input mellett kiválasztódik másik nyelv akkor a form összes ilyen nyelv választós eleme átáll az adott nyelvre.

**Comment by kailniris** [comment]
@ymycorp 
Form mentéskor bad request jön vissza.
"The field name is required at least in Hungarian."

active: "1"
description: {1: "Kisker vevők ide jönnek", 2: "Kisker vevők ide jönnek", 4: "Kisker vevők ide jönnek",…}
id_partner_category: "1"
name: {1: "Kisker vevő", 2: "Kisker vevő2", 4: "Kisker vevő", 6: "Kisker vevő3"}
1: "Kisker vevő"
2: "Kisker vevő2"
4: "Kisker vevő"
6: "Kisker vevő3"
reduction: "0"
submitAddpartner_category: ""

**Comment by ymycorp** [comment]
Az alábbi módon kell visszajönni a mezőknek:
name_1 : value
name_2 : value

Tehát nem tömbben, hanem külön külön elemenként. Az elem neve majd alsó vonás és a nyelv azonosító.

**Comment by kailniris** [comment]
Át lehetne ezt alakítani szerver oldalt? Úgy van most megcsinálna hogy minden form úgy van elküldve ahogy jön így nem kell kivételeket kezelni ami elég körülményes lenne, főleg ha csak 1-2 elemnél kellene.

**Comment by ymycorp** [comment]
Megcsináltam, már megeszi a tömböt is ilyen helyeken.
