### ISSUE TITLE
Egyszerű elemek

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#30]
Van 3 egyszerű elem ezek:  

{elseif $field.type == 'header1'}    
                   <h3>{$field.content}</h3>

{elseif $field.type == 'header2'}    
                        <h4>{$field.content}</h4>   

{elseif $field.type == 'line'}    
                        <hr>

**Comment by kailniris** [comment]
@ymycorp 
Partner törzs -> sor szerkesztése -> Címkék menüpontban a header2 nem nincs értéke. "Új cím hozzáadása" kéne lennie.
Header1 és line elemeket, hol találok?

**Comment by ymycorp** [comment]
Az értéket javítottam. A konverter még nem ismerte ezt az elemet..
Header 1 és line szerintem sehol sincs használva jelenleg.
A lenti képen látszik a jelenlegi forrása.

![image](https://user-images.githubusercontent.com/10480509/54706299-df6c8f00-4b3e-11e9-9ff1-da12642e9801.png)
