### ISSUE TITLE
A submit gomb értéke mindig legyen 1

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#31]
A submit gomb értéke mindig legyen 1, mert szerver oldalon a null értelmezése bizonytalan.

**Comment by kailniris** [comment]
@ymycorp Szerver oldalon nem lehet ezeknek a gomboknak értéket adni? Egyszerűbb lenne ha már azzal az értékkel jönne le a form submit tulajdonság amivel vissza is kell küldeni.

**Comment by ymycorp** [comment]
Pár helyen már beállítottam, de sok helyen kell átírni. Itt egyszerűbbnek
gondoltam.

Üdvözlettel: / Best regards, / Cordialement, / Mit freundlichen Grüssen:
 Ádám Imre

**Comment by kailniris** [comment]
Az a baj, hogy mindenhol más az submit kulcs neve és elég spagetti lenne emiatt a kód.
