### ISSUE TITLE
Dinamikus tábla

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#32]
A dinamikus tábla az alábbi helyen található: program beállítások/modulok adminisztráció fül CRM modul beállítás pipe setup fül.
Add new line-ra szúrja be a sablon sort.

**Comment by kailniris** [comment]
Itt van egy olyan 0. lépéses baj, hogy amikor be akarok lépni a menüpontba akkor Form view kéne, hogy betöltsön és nem grid. Amikor a navigációs listát letöltöm kéne, valami megkülönböztető ami alapján meg tudom állapítani, hogy Grids vagy Forms view-et töltsek be.

**Comment by ymycorp** [comment]
A content_template elem mondja meg, hogy melyik sablon kell.

Üdvözlettel: / Best regards, / Cordialement, / Mit freundlichen Grüssen:
 Ádám Imre

**Comment by kailniris** [comment]
@ymycorp PHP miatt nem elérhető a form

> Fatal error: Uncaught Error: Class 'Touchpoint' not found in /home/ymycorph/public_html/erp_dev/core/modules/crm/crm.php:1088 Stack trace: #0 /home/ymycorph/public_html/erp_dev/core/modules/crm/crm.php(1219): Crm->_displayForm() #1 /home/ymycorph/public_html/erp_dev/core/tabs/AdminModules.php(177): Crm->getContent() #2 /home/ymycorph/public_html/erp_dev/core/classes/AdminTab.php(315): AdminModules->postProcess() #3 /home/ymycorph/public_html/erp_dev/core/index.php(70): AdminTabCore->run() #4 /home/ymycorph/public_html/erp_dev/dev/index.php(4): require('/home/ymycorph/...') #5 {main} thrown in /home/ymycorph/public_html/erp_dev/core/modules/crm/crm.php on line 1088
