### ISSUE TITLE
Timeline elem

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#34]
Kimaradt a listámból a timeline elem.
A CRM/ügyeknél a formon az üzenetek fülön van ilyen.

Ez az implementációja jelenleg:
![image](https://user-images.githubusercontent.com/10480509/54831325-6d20b980-4cba-11e9-847e-2d6fbcad6a97.png)

**Comment by kailniris** [comment]
@ymycorp Nem tudok ügyet létrehozni, hogy tudjam ezt tesztelni.

**Comment by ymycorp** [comment]
Miért nem megy az ügy létrehozás? 
Nálam meg, de hozzád rendeltem a 7-es ügyet azt látnod kéne, és van is üzenet pár darab
