### ISSUE TITLE
CRM/ elintézendők és ügyek nem megy.

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#39]
CRM/ elintézendők és ügyek nem megy. Az ikonok néha csak képek, funkció nélkül.
A hibaüzenet:
TypeError: "col.icons[col.value] is undefined"

**Comment by kailniris** [comment]
@ymycorp CRM/ elintézendők-nél az a baj, hogy az icon oszlop értéke az "0" de a lehetséges icon-ok azok true vagy false értékekből választhatók. Ezt tudnánk javítani szerver oldalt, hogy az érték false legyen 0 helyett és true legyen 1 helyett. Akkor megjavulna ez a dolog. A CRM/elintézendőknél a régi programban nem tudok új sort létrehozni. Meg tudnád azt nézni?

**Comment by ymycorp** [comment]
Az ikonnál meg kéne csinálni, hogy mint a true/false, mint a 0/1 esetet tudja, mert ez sql-ből így jön
ahogy nézem ez szám mindenhol
konvertálni integerre esetleg előtte
