### ISSUE TITLE
Editor elem

### ISSUE THREAD

**Issue by ymycorp** [ymycorp/ERP_frontend#56]
Ez egy szövegszerkesztő szokásos funkciókkal. Q editor tökéletes ide.
Ennek csak value-ja van.

**Comment by kailniris** [comment]
@ymycorp Hol találok ilyen elemet?

**Comment by ymycorp** [comment]
Majd a fordítások/ email sablonok alatt lesz, de az még részemről nincs kész. ha megvan akkor tudom majd tesztelni. Min 1 hét kell még hozzá
